name: Publish Package to npmjs

on:
    push:
        branches:
            - master

env:
    NODE_VERSION: '14.x'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: 'npm'

            - name: npm install
              run: |
                  npm ci
                  npm run build --if-present
            - name: Zip artifact for deployment
              run: zip release.zip . -r

            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v3
              with:
                  name: node-app
                  path: release.zip
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v3
              with:
                  name: node-app

            - name: unzip artifact for deployment
              run: unzip release.zip && rm release.zip

            - name: 'Deploy to Cookiebot'
              uses: Huddly/cookiebot-deploy@master
              with:
                  login_email: ${{ secrets.COOKIEBOT_EMAIL }}
                  login_password: ${{ secrets.COOKIEBOT_PASSWORD }}
